<a href="https://colab.research.google.com/github/sabikunnahar16/PythonProjectLab/blob/main/Lab8ASSignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df=pd.read_csv('/content/Fuel_Consumption_2000-2022.csv')
print(df)
# Display the first 5 rows (default)
print("First 5 rows of the DataFrame:")
print(df.head())

# Display the last 5 rows (default)
print("\nLast 5 rows of the DataFrame:")
print(df.tail())

# Generate descriptive statistics
print("\nDescriptive Statistics:")
print(df.describe())

# Provide concise summary of the DataFrame
print("\nInfo about the DataFrame:")
print(df.info())

# Compute mean, median, min, max
print("\nMean of numeric columns:")
print(df.mean(numeric_only=True))

print("\nMedian of numeric columns:")
print(df.median(numeric_only=True))

print("\nMinimum values in each column:")
print(df.min(numeric_only=True))

print("\nMaximum values in each column:")
print(df.max(numeric_only=True))

# Compute sum, count, standard deviation, variance
print("\nSum of numeric columns:")
print(df.sum(numeric_only=True))

print("\nCount of numeric columns:")
print(df.count(numeric_only=True))

print("\nStandard deviation of numeric columns:")
print(df.std(numeric_only=True))

print("\nVariance of numeric columns:")
print(df.var(numeric_only=True))

# Fill missing values with 0
df_filled = df.fillna(0)
print("\nDataFrame after filling NaN values with 0:")
print(df_filled.head())

# Drop rows with missing values
df_dropped_rows = df.dropna(axis=0, how='any')
print("\nDataFrame after dropping rows with NaN values:")
print(df_dropped_rows.head())

# Drop columns with missing values
df_dropped_columns = df.dropna(axis=1, how='any')
print("\nDataFrame after dropping columns with NaN values:")
print(df_dropped_columns.head())

# Sort the DataFrame by a specific column in descending order (change column name accordingly)
sorted_df = df.sort_values(by='CO2 Emissions(g/km)', ascending=False)
print("\nDataFrame sorted by CO2 Emissions in descending order:")
print(sorted_df.head())

# Group by a specific column (change column name accordingly)
grouped_df = df.groupby('Fuel Type').mean(numeric_only=True)
print("\nGrouped DataFrame by Fuel Type with mean values:")
print(grouped_df)

# Create a pivot table
pivot = df.pivot_table(values='CO2 Emissions(g/km)', index='Fuel Type', columns='Cylinders', aggfunc='mean')
print("\nPivot Table:")
print(pivot)

# Apply a function (Example: Convert CO2 emissions to pounds per mile)
df['CO2 Pounds/mile'] = df['CO2 Emissions(g/km)'].apply(lambda x: x * 0.00220462)
print("\nDataFrame after applying function to convert CO2 emissions to pounds per mile:")
print(df.head())

       YEAR   MAKE        MODEL  VEHICLE CLASS  ENGINE SIZE  CYLINDERS  \
0      2000  ACURA        1.6EL        COMPACT          1.6          4
1      2000  ACURA        1.6EL        COMPACT          1.6          4
2      2000  ACURA        3.2TL       MID-SIZE          3.2          6
3      2000  ACURA        3.5RL       MID-SIZE          3.5          6
4      2000  ACURA      INTEGRA     SUBCOMPACT          1.8          4
...     ...    ...          ...            ...          ...        ...
22551  2022  Volvo  XC40 T5 AWD     SUV: Small          2.0          4
22552  2022  Volvo  XC60 B5 AWD     SUV: Small          2.0          4
22553  2022  Volvo  XC60 B6 AWD     SUV: Small          2.0          4
22554  2022  Volvo  XC90 T5 AWD  SUV: Standard          2.0          4
22555  2022  Volvo  XC90 T6 AWD  SUV: Standard          2.0          4

      TRANSMISSION FUEL  FUEL CONSUMPTION  HWY (L/100 km)  COMB (L/100 km)  \
0               A4    X               9.2             6.7              8.1
1               M5    X               8.5             6.5              7.6
2              AS5    Z              12.2             7.4             10.0
3               A4    Z              13.4             9.2             11.5
4               A4    X              10.0             7.0              8.6
...            ...  ...               ...             ...              ...
22551          AS8    Z              10.7             7.7              9.4
22552          AS8    Z              10.5             8.1              9.4
22553          AS8    Z              11.0             8.7              9.9
22554          AS8    Z              11.5             8.4             10.1
22555          AS8    Z              12.4             8.9             10.8

       COMB (mpg)  EMISSIONS
0              35        186
1              37        175
2              28        230
3              25        264
4              33        198
...           ...        ...
22551          30        219
22552          30        219
22553          29        232
22554          28        236
22555          26        252

[22556 rows x 13 columns]
First 5 rows of the DataFrame:
   YEAR   MAKE    MODEL VEHICLE CLASS  ENGINE SIZE  CYLINDERS TRANSMISSION  \
0  2000  ACURA    1.6EL       COMPACT          1.6          4           A4
1  2000  ACURA    1.6EL       COMPACT          1.6          4           M5
2  2000  ACURA    3.2TL      MID-SIZE          3.2          6          AS5
3  2000  ACURA    3.5RL      MID-SIZE          3.5          6           A4
4  2000  ACURA  INTEGRA    SUBCOMPACT          1.8          4           A4

  FUEL  FUEL CONSUMPTION  HWY (L/100 km)  COMB (L/100 km)  COMB (mpg)  \
0    X               9.2             6.7              8.1          35
1    X               8.5             6.5              7.6          37
2    Z              12.2             7.4             10.0          28
3    Z              13.4             9.2             11.5          25
4    X              10.0             7.0              8.6          33

   EMISSIONS
0        186
1        175
2        230
3        264
4        198

Last 5 rows of the DataFrame:
       YEAR   MAKE        MODEL  VEHICLE CLASS  ENGINE SIZE  CYLINDERS  \
22551  2022  Volvo  XC40 T5 AWD     SUV: Small          2.0          4
22552  2022  Volvo  XC60 B5 AWD     SUV: Small          2.0          4
22553  2022  Volvo  XC60 B6 AWD     SUV: Small          2.0          4
22554  2022  Volvo  XC90 T5 AWD  SUV: Standard          2.0          4
22555  2022  Volvo  XC90 T6 AWD  SUV: Standard          2.0          4

      TRANSMISSION FUEL  FUEL CONSUMPTION  HWY (L/100 km)  COMB (L/100 km)  \
22551          AS8    Z              10.7             7.7              9.4
22552          AS8    Z              10.5             8.1              9.4
22553          AS8    Z              11.0             8.7              9.9
22554          AS8    Z              11.5             8.4             10.1
22555          AS8    Z              12.4             8.9             10.8

       COMB (mpg)  EMISSIONS
22551          30        219
22552          30        219
22553          29        232
22554          28        236
22555          26        252

Descriptive Statistics:
               YEAR   ENGINE SIZE     CYLINDERS  FUEL CONSUMPTION  \
count  22556.000000  22556.000000  22556.000000      22556.000000
mean    2011.554442      3.356646      5.854141         12.763513
std        6.298269      1.335425      1.819597          3.500999
min     2000.000000      0.800000      2.000000          3.500000
25%     2006.000000      2.300000      4.000000         10.400000
50%     2012.000000      3.000000      6.000000         12.300000
75%     2017.000000      4.200000      8.000000         14.725000
max     2022.000000      8.400000     16.000000         30.600000

       HWY (L/100 km)  COMB (L/100 km)    COMB (mpg)     EMISSIONS
count    22556.000000     22556.000000  22556.000000  22556.000000
mean         8.919126        11.034341     27.374534    250.068452
std          2.274764         2.910920      7.376982     59.355276
min          3.200000         3.600000     11.000000     83.000000
25%          7.300000         9.100000     22.000000    209.000000
50%          8.400000        10.600000     27.000000    243.000000
75%         10.200000        12.700000     31.000000    288.000000
max         20.900000        26.100000     78.000000    608.000000

Info about the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22556 entries, 0 to 22555
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   YEAR              22556 non-null  int64
 1   MAKE              22556 non-null  object
 2   MODEL             22556 non-null  object
 3   VEHICLE CLASS     22556 non-null  object
 4   ENGINE SIZE       22556 non-null  float64
 5   CYLINDERS         22556 non-null  int64
 6   TRANSMISSION      22556 non-null  object
 7   FUEL              22556 non-null  object
 8   FUEL CONSUMPTION  22556 non-null  float64
 9   HWY (L/100 km)    22556 non-null  float64
 10  COMB (L/100 km)   22556 non-null  float64
 11  COMB (mpg)        22556 non-null  int64
 12  EMISSIONS         22556 non-null  int64
dtypes: float64(4), int64(4), object(5)
memory usage: 2.2+ MB
None

Mean of numeric columns:
YEAR                2011.554442
ENGINE SIZE            3.356646
CYLINDERS              5.854141
FUEL CONSUMPTION      12.763513
HWY (L/100 km)         8.919126
COMB (L/100 km)       11.034341
COMB (mpg)            27.374534
EMISSIONS            250.068452
dtype: float64

Median of numeric columns:
YEAR                2012.0
ENGINE SIZE            3.0
CYLINDERS              6.0
FUEL CONSUMPTION      12.3
HWY (L/100 km)         8.4
COMB (L/100 km)       10.6
COMB (mpg)            27.0
EMISSIONS            243.0
dtype: float64

Minimum values in each column:
YEAR                2000.0
ENGINE SIZE            0.8
CYLINDERS              2.0
FUEL CONSUMPTION       3.5
HWY (L/100 km)         3.2
COMB (L/100 km)        3.6
COMB (mpg)            11.0
EMISSIONS             83.0
dtype: float64

Maximum values in each column:
YEAR                2022.0
ENGINE SIZE            8.4
CYLINDERS             16.0
FUEL CONSUMPTION      30.6
HWY (L/100 km)        20.9
COMB (L/100 km)       26.1
COMB (mpg)            78.0
EMISSIONS            608.0
dtype: float64

Sum of numeric columns:
YEAR                45372622.0
ENGINE SIZE            75712.5
CYLINDERS             132046.0
FUEL CONSUMPTION      287893.8
HWY (L/100 km)        201179.8
COMB (L/100 km)       248890.6
COMB (mpg)            617460.0
EMISSIONS            5640544.0
dtype: float64

Count of numeric columns:
YEAR                22556
ENGINE SIZE         22556
CYLINDERS           22556
FUEL CONSUMPTION    22556
HWY (L/100 km)      22556
COMB (L/100 km)     22556
COMB (mpg)          22556
EMISSIONS           22556
dtype: int64

Standard deviation of numeric columns:
YEAR                 6.298269
ENGINE SIZE          1.335425
CYLINDERS            1.819597
FUEL CONSUMPTION     3.500999
HWY (L/100 km)       2.274764
COMB (L/100 km)      2.910920
COMB (mpg)           7.376982
EMISSIONS           59.355276
dtype: float64

Variance of numeric columns:
YEAR                  39.668195
ENGINE SIZE            1.783360
CYLINDERS              3.310934
FUEL CONSUMPTION      12.256993
HWY (L/100 km)         5.174551
COMB (L/100 km)        8.473455
COMB (mpg)            54.419860
EMISSIONS           3523.048828
dtype: float64

DataFrame after filling NaN values with 0:
   YEAR   MAKE    MODEL VEHICLE CLASS  ENGINE SIZE  CYLINDERS TRANSMISSION  \
0  2000  ACURA    1.6EL       COMPACT          1.6          4           A4
1  2000  ACURA    1.6EL       COMPACT          1.6          4           M5
2  2000  ACURA    3.2TL      MID-SIZE          3.2          6          AS5
3  2000  ACURA    3.5RL      MID-SIZE          3.5          6           A4
4  2000  ACURA  INTEGRA    SUBCOMPACT          1.8          4           A4

  FUEL  FUEL CONSUMPTION  HWY (L/100 km)  COMB (L/100 km)  COMB (mpg)  \
0    X               9.2             6.7              8.1          35
1    X               8.5             6.5              7.6          37
2    Z              12.2             7.4             10.0          28
3    Z              13.4             9.2             11.5          25
4    X              10.0             7.0              8.6          33

   EMISSIONS
0        186
1        175
2        230
3        264
4        198

DataFrame after dropping rows with NaN values:
   YEAR   MAKE    MODEL VEHICLE CLASS  ENGINE SIZE  CYLINDERS TRANSMISSION  \
0  2000  ACURA    1.6EL       COMPACT          1.6          4           A4
1  2000  ACURA    1.6EL       COMPACT          1.6          4           M5
2  2000  ACURA    3.2TL      MID-SIZE          3.2          6          AS5
3  2000  ACURA    3.5RL      MID-SIZE          3.5          6           A4
4  2000  ACURA  INTEGRA    SUBCOMPACT          1.8          4           A4

  FUEL  FUEL CONSUMPTION  HWY (L/100 km)  COMB (L/100 km)  COMB (mpg)  \
0    X               9.2             6.7              8.1          35
1    X               8.5             6.5              7.6          37
2    Z              12.2             7.4             10.0          28
3    Z              13.4             9.2             11.5          25
4    X              10.0             7.0              8.6          33

   EMISSIONS
0        186
1        175
2        230
3        264
4        198

DataFrame after dropping columns with NaN values:
   YEAR   MAKE    MODEL VEHICLE CLASS  ENGINE SIZE  CYLINDERS TRANSMISSION  \
0  2000  ACURA    1.6EL       COMPACT          1.6          4           A4
1  2000  ACURA    1.6EL       COMPACT          1.6          4           M5
2  2000  ACURA    3.2TL      MID-SIZE          3.2          6          AS5
3  2000  ACURA    3.5RL      MID-SIZE          3.5          6           A4
4  2000  ACURA  INTEGRA    SUBCOMPACT          1.8          4           A4

  FUEL  FUEL CONSUMPTION  HWY (L/100 km)  COMB (L/100 km)  COMB (mpg)  \
0    X               9.2             6.7              8.1          35
1    X               8.5             6.5              7.6          37
2    Z              12.2             7.4             10.0          28
3    Z              13.4             9.2             11.5          25
4    X              10.0             7.0              8.6          33

   EMISSIONS
0        186
1        175
2        230
3        264
4        198

KeyError: 'CO2 Emissions(g/km)'